[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SEEM"
version = "1.0"
description = "Segment Everything Everywhere All at Once."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

dependencies = [   
]


[project.urls]
"Paper" = "https://arxiv.org/abs/2304.06718"
"Code" = "https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/tree/v1.0"
"Bug Tracker" = "https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/issues"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["assets*"]

[tool.wheel]
exclude = ["assets*"]
